#!/usr/bin/env python3
"""Summarize the executed 100-step HJ/PIL factorial screening runs.

The screen is deliberately kept separate from the frozen 1,200-step protocol:
it is a compute-bounded follow-up from the final BASE EMA checkpoint, with a
fixed 128-sample audit and a fixed real descriptor reference.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


RUN_ROOT = Path(os.environ.get("IRIS_RUN_ROOT", "/private/tmp/iris_gated_run"))
REPORT = Path(os.environ.get("IRIS_REPORT_DIR", str(Path(__file__).resolve().parents[1])))
SCREEN = RUN_ROOT / "work" / "runs" / "physics_screening_2026"
BASE = RUN_ROOT / "work" / "runs" / "base_local_resume"
FIG = REPORT / "figures"
TABLE = REPORT / "tables"
ARTIFACT = REPORT / "artifacts"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text())


def final_history(path: Path) -> dict:
    rows = json.loads(path.read_text())
    return rows[-1] if rows else {}


def scalar(v: object) -> float:
    return float(v) if v is not None else float("nan")


def row_for(condition: str, audit_path: Path, cfg_path: Path, history_path: Path) -> dict:
    m = load_json(audit_path)
    cfg = load_json(cfg_path)
    h = final_history(history_path)
    return {
        "condition": condition,
        "training_steps": int(cfg.get("steps_completed", cfg.get("steps", 0))),
        "positive_rows": int(cfg.get("train_rows", cfg.get("positive_rows", 489 if condition == "base" else 0))),
        "positive_groups": int(cfg.get("train_groups", cfg.get("positive_groups", 125 if condition == "base" else 0))),
        "generic_ratio_to_real_p90": scalar(m.get("generic_distance_to_real_baseline_ratio")),
        "generic_gate_pass": bool(m.get("generic_fidelity_gate_pass", False)),
        "hard_geometry_distance": scalar(m.get("hard_geometry_standardized_energy_distance")),
        "hard_pil_distance": scalar(m.get("hard_pil_standardized_energy_distance")),
        "flux_median_ratio": scalar(m.get("synthetic_to_real_flux_median_ratio")),
        "active_area_median_ratio": scalar(m.get("synthetic_to_real_active_area_median_ratio")),
        "diversity_ratio": scalar(m.get("synthetic_to_real_diversity_ratio")),
        "saturation_fraction": scalar(m.get("synthetic_saturation_fraction_abs_gt_2900G")),
        "final_loss": scalar(h.get("loss")),
        "final_denoise_loss": scalar(h.get("denoise")),
        "final_generic_loss": scalar(h.get("generic")),
        "final_hj_loss": scalar(h.get("hj")),
        "final_pil_loss": scalar(h.get("pil")),
        "audit_path": str(audit_path),
        "checkpoint_path": str(SCREEN / condition / "generator.pt"),
    }


def write_table(df: pd.DataFrame) -> None:
    columns = [
        "condition", "training_steps", "positive_rows", "positive_groups",
        "generic_ratio_to_real_p90", "generic_gate_pass",
        "hard_geometry_distance", "hard_pil_distance", "flux_median_ratio",
        "active_area_median_ratio", "diversity_ratio", "saturation_fraction",
        "final_denoise_loss", "final_generic_loss", "final_hj_loss", "final_pil_loss",
    ]
    out = df[columns].copy()
    out.to_csv(TABLE / "physics_screening.csv", index=False)
    lines = [
        "% Generated by scripts/build_physics_screening_artifacts.py.",
        r"\begin{tabular}{lrrrrrrrr}",
        r"\toprule",
        r"Arm & Steps & $N_+$ & Groups & Gen. ratio & Gate & HJ dist. & PIL dist. \\",
        r"\midrule",
    ]
    for r in out.itertuples(index=False):
        condition = str(r.condition).replace("_", "\\_")
        lines.append(
            f"\\texttt{{{condition}}} & {r.training_steps} & {r.positive_rows} & {r.positive_groups} "
            f"& {r.generic_ratio_to_real_p90:.3f} & {'PASS' if r.generic_gate_pass else 'FAIL'} "
            f"& {r.hard_geometry_distance:.3f} & {r.hard_pil_distance:.3f} \\\\" 
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    (TABLE / "physics_screening.tex").write_text("\n".join(lines) + "\n")


def write_figures(df: pd.DataFrame) -> None:
    labels = df.condition.tolist()
    colors = ["#1769aa", "#18864b", "#d97706", "#7c3aed"]
    x = np.arange(len(df))

    fig, axes = plt.subplots(1, 2, figsize=(11, 4.6), constrained_layout=True)
    axes[0].bar(x, df.generic_ratio_to_real_p90, color=colors)
    axes[0].axhline(8.0, color="#b42318", linestyle="--", linewidth=1.4, label="gate = 8")
    axes[0].set_title("Corrected generic distance")
    axes[0].set_ylabel("distance / real split-half p90")
    axes[0].set_xticks(x, labels)
    axes[0].legend(frameon=False)
    axes[0].set_ylim(0, max(24, float(df.generic_ratio_to_real_p90.max()) * 1.12))

    width = 0.36
    axes[1].bar(x - width / 2, df.hard_geometry_distance, width, label="HJ geometry", color="#1769aa")
    axes[1].bar(x + width / 2, df.hard_pil_distance, width, label="strong-PIL", color="#d97706")
    axes[1].set_title("Hard physical descriptor distances")
    axes[1].set_ylabel("standardized energy distance")
    axes[1].set_xticks(x, labels)
    axes[1].legend(frameon=False)
    fig.savefig(FIG / "physics_screening_comparison.png", dpi=300, facecolor="white")
    fig.savefig(FIG / "physics_screening_comparison.pdf", facecolor="white")
    plt.close(fig)

    fig, axes = plt.subplots(2, 2, figsize=(10, 7), constrained_layout=True)
    metric_specs = [("final_denoise_loss", "denoise"), ("final_generic_loss", "generic"), ("final_hj_loss", "HJ"), ("final_pil_loss", "PIL")]
    for ax, (column, title) in zip(axes.ravel(), metric_specs):
        vals = df[column].to_numpy(float)
        ax.bar(x, vals, color=colors)
        ax.set_title(f"Final {title} loss")
        ax.set_xticks(x, labels)
        ax.set_ylabel("loss")
    fig.savefig(FIG / "physics_screening_losses.png", dpi=300, facecolor="white")
    fig.savefig(FIG / "physics_screening_losses.pdf", facecolor="white")
    plt.close(fig)


def main() -> None:
    FIG.mkdir(parents=True, exist_ok=True)
    TABLE.mkdir(parents=True, exist_ok=True)
    ARTIFACT.mkdir(parents=True, exist_ok=True)
    rows = []
    base_metrics = BASE / "audit" / "v2_manipulation_metrics.json"
    base_cfg = BASE / "outputs" / "base" / "run_config_resume.json"
    base_hist = BASE / "outputs" / "base" / "training_history_resume.json"
    # The base configuration is a resume receipt, while the screen configs are
    # direct positive-only fine-tune receipts; both are retained verbatim.
    rows.append(row_for("base", base_metrics, base_cfg, base_hist))
    for condition in ("hj", "pil", "hj_pil"):
        rows.append(row_for(
            condition,
            SCREEN / f"{condition}_audit" / "v2_manipulation_metrics.json",
            SCREEN / condition / "run_config.json",
            SCREEN / condition / "training_history.json",
        ))
    df = pd.DataFrame(rows)
    write_table(df)
    write_figures(df)
    payload = {
        "experiment": "IRIS v2 physics factorial screening",
        "screen_type": "100-step positive-only fine-tune from frozen BASE EMA; exploratory, not confirmatory",
        "checkpoint_source": str(BASE / "outputs" / "base" / "generator.pt"),
        "fixed_real_reference": str(BASE / "audit"),
        "conditions": ["base", "hj", "pil", "hj_pil"],
        "shared": {
            "seed": 2026,
            "positive_rows": 489,
            "positive_groups": 125,
            "screen_steps": 100,
            "diffusion_steps": 100,
            "base_channels": 24,
            "batch_size": 16,
            "physics_batch_size": 16,
            "lambda_generic": 0.08,
            "lambda_hj": 0.05,
            "lambda_pil": 0.05,
            "physics_warmup_steps": 200,
            "physics_max_t_frac": 0.25,
            "ema_decay": 0.995,
            "ema_warmup_steps": 100,
            "lr": 0.0001,
            "lr_schedule": "cosine",
            "sampling_steps": 50,
            "synthetic_count_per_arm": 128,
            "real_reference_count": 248,
            "prepared_tensor_cache": str(RUN_ROOT / "work" / "prepared" / "positive_train_pergroup4"),
        },
        "rows": rows,
        "interpretation": [
            "All three screen arms activated their intended differentiable physics loss.",
            "All three screen arms failed the broad corrected generic gate at 100 steps; this is an early-training diagnostic, not evidence that a full arm cannot converge.",
            "No downstream forecasting or test-set selection was performed from these screens.",
        ],
    }
    (ARTIFACT / "physics_screening_metrics.json").write_text(json.dumps(payload, indent=2, allow_nan=True) + "\n")
    print(json.dumps({"conditions": len(rows), "table": str(TABLE / "physics_screening.csv"), "figures": 2}, indent=2))


if __name__ == "__main__":
    main()
